server:
  port: 8002

spring:
  security:
    jwt:
      key: assdfwsfwfw
      expire: 7
    filter:
      order: -100
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml

  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    sentinel:
      transport:
        dashboard: localhost:8858

cors:
  order: -102

short-link:
  group:
    max-num: 20
